### ISSUE TITLE
Disabling PATCH, DELETE and POST

### ISSUE THREAD

**Issue by mahlu** [holidayextras/jsonapi-server#106]
How to allow only the GET and OPTIONS method on a type?

**Comment by theninj4** [comment]
If you want to restrict access to a resource you should simply remove the associated functionality from your handler. Handlers are documented here: https://github.com/holidayextras/jsonapi-server/blob/master/documentation/handlers.md

**Comment by mahlu** [comment]
Thanks!

**Comment by mahlu** [comment]
Not working yet...
if I remove the associated functionality I get an error:
...
`MongoStore.prototype = _.omit(MongoStore.prototype, ['create', 'update', 'delete'])`
`module.exports = new MongoStore(db)`


C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\lib\handlerEnforcer.js:29
    original.apply(handlers, argsIn);
            ^

TypeError: Cannot read property 'apply' of undefined
    at Object.create (C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\lib\handlerEnforcer.js:29:13)
    at async.waterfall.newResource (C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\lib\routes\create.js:46:33)
    at fn (C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:746:34)
    at C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:1213:16
    at C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:166:37
    at C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:706:43
    at C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:167:37
    at Immediate._onImmediate (C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:516:17)

**Comment by theninj4** [comment]
Oh! I see the problem now, sorry. I'll sort this out.
