### ISSUE TITLE
Invalid resource includes throw an error

### ISSUE THREAD

**Issue by adamlc** [holidayextras/jsonapi-server#208]
When trying to include resources that have an invalid name, i.e. **http://localhost:16006/rest/articles?include=fdfdds** an error is thrown. 

In the MemoryHandler this returns the correct response but in some other handlers it actually kills the node process. Here is a stack trace:

```
Error: Callback was already called.
    at /Users/mooloop/Sites/jsonapi-server/node_modules/async/dist/async.js:985:32
    at includePP._fillIncludeTree.fiErr (/Users/mooloop/Sites/jsonapi-server/lib/postProcessing/include.js:33:14)
    at /Users/mooloop/Sites/jsonapi-server/node_modules/async/dist/async.js:484:16
    at /Users/mooloop/Sites/jsonapi-server/node_modules/async/dist/async.js:1161:9
    at /Users/mooloop/Sites/jsonapi-server/node_modules/async/dist/async.js:484:16
    at iteratorCallback (/Users/mooloop/Sites/jsonapi-server/node_modules/async/dist/async.js:1084:13)
    at /Users/mooloop/Sites/jsonapi-server/node_modules/async/dist/async.js:988:16
    at /Users/mooloop/Sites/jsonapi-server/node_modules/async/dist/async.js:1158:13
    at /Users/mooloop/Sites/jsonapi-server/node_modules/async/dist/async.js:484:16
    at /Users/mooloop/Sites/jsonapi-server/node_modules/async/dist/async.js:1161:9
```

I've attempted to fix the issue, although I'm not actually sure of the implications, it seems to work for me but I wanted to start a discussion first before I open a PR. Basically I've added a callbackAlreadyCalled variable that checks if the callback has already been called. Although it works I feel like it isn't really the best solution, it should probably be done up the chain somewhere to ensure it never gets called in the first place!

lib/postProcessing/include.js:

``` javascript
includePP.action = (request, response, callback) => {
  let includes = request.params.include
  let callbackAlreadyCalled = false
  const filters = request.params.filter || { }
  if (!includes) return callback()
  includes = (`${includes}`).split(',')

  includePP._arrayToTree(request, includes, filters, (attErr, includeTree) => {
    if (attErr && !callbackAlreadyCalled) {
      callbackAlreadyCalled = true
      return callback(attErr)
    }

    let dataItems = response.data
    if (!(dataItems instanceof Array)) dataItems = [ dataItems ]
    includeTree._dataItems = dataItems

    includePP._fillIncludeTree(includeTree, request, fiErr => {
      if (fiErr && !callbackAlreadyCalled) {
        callbackAlreadyCalled = true
        return callback(fiErr)
      }

      includeTree._dataItems = [ ]
      response.included = includePP._getDataItemsFromTree(includeTree)
      response.included = _.uniqBy(response.included, someItem => `${someItem.type}~~${someItem.id}`)

      if (!callbackAlreadyCalled) {
        callbackAlreadyCalled = true
        return callback()
      }
    })
  })
}
```

**Comment by theninj4** [comment]
Ahhh nice find! The bug was a few lines further down, here's the simplified view of root cause:
```javascript
includePP._arrayToTree = (request, includes, filters, callback) => {

  const iterate = (text, node, filter) => {
    if (error) return callback("ERROR");
  }
  
  includes.forEach(include => {
    iterate(include, tree, filters)
  })

  return callback(null, tree)
}
```
The `includes.forEach` would trigger the error callback, however as the stack unwinds we end up back in the `forEach`, which falls down to the final `return callback` for the second invalid invocation.
