### ISSUE TITLE
GraphQL schema conversion starts regardless of its configuration and throw errors due to its limitations

### ISSUE THREAD

**Issue by yossialush** [holidayextras/jsonapi-server#239]
While trying to update jsonapi-server to 2.3.0 I've encountered some issues:
For the following resource schema
```
{
        resource: ResourcesNames.ITEM,
        handlers: handler,
        attributes: {
            responseType: jsonApi.Joi.object().keys({
                id: jsonApi.Joi.number().integer().required(),
                name: jsonApi.Joi.string()
            }).required(),
            instructions: jsonApi.Joi.array().items(jsonApi.Joi.object().keys({
                id: jsonApi.Joi.number().integer(),
                type: jsonApi.Joi.object().keys({
                    id: jsonApi.Joi.number().integer().required(),
                    name: jsonApi.Joi.string()
                }).required(),
                data: jsonApi.Joi.string().optional()
            })).optional()
        }
    }
```
 I get the following error
```
Error: Joi arrays must contain a single type
    at Object.joiConverter.simpleAttribute.joiScheme [as simpleAttribute] (/opt/checklists_service/services/web-api-gateway/node_modules/jsonapi-server/lib/graphQl/joiConverter.js:30:13)
    at Object.joiConverter.swap (/opt/checklists_service/services/web-api-gateway/node_modules/jsonapi-server/lib/graphQl/joiConverter.js:46:25)
    at Object.keys.forEach.attribute (/opt/checklists_service/services/web-api-gateway/node_modules/jsonapi-server/lib/graphQl/readTypes.js:41:30)
    at Array.forEach (native)
    at fields (/opt/checklists_service/services/web-api-gateway/node_modules/jsonapi-server/lib/graphQl/readTypes.js:36:46)
    at resolveThunk (/opt/checklists_service/services/web-api-gateway/node_modules/graphql/type/definition.js:115:40)
    at defineFieldMap (/opt/checklists_service/services/web-api-gateway/node_modules/graphql/type/definition.js:265:18)
    at GraphQLObjectType.getFields (/opt/checklists_service/services/web-api-gateway/node_modules/graphql/type/definition.js:235:44)
    at /opt/checklists_service/services/web-api-gateway/node_modules/graphql/type/schema.js:207:27
    at typeMapReducer (/opt/checklists_service/services/web-api-gateway/node_modules/graphql/type/schema.js:219:7)
    at typeMapReducer (/opt/checklists_service/services/web-api-gateway/node_modules/graphql/type/schema.js:187:12)
    at /opt/checklists_service/services/web-api-gateway/node_modules/graphql/type/schema.js:217:22
    at Array.forEach (native)
    at /opt/checklists_service/services/web-api-gateway/node_modules/graphql/type/schema.js:208:29
    at typeMapReducer (/opt/checklists_service/services/web-api-gateway/node_modules/graphql/type/schema.js:219:7)
    at Array.reduce (native)
    at new GraphQLSchema (/opt/checklists_service/services/web-api-gateway/node_modules/graphql/type/schema.js:95:34)
    at Object.jsonApiGraphQL.generate.allResourceConfig [as generate] (/opt/checklists_service/services/web-api-gateway/node_modules/jsonapi-server/lib/graphQl/index.js:29:10)
    at Object.jsonApiGraphQL.with.app [as with] (/opt/checklists_service/services/web-api-gateway/node_modules/jsonapi-server/lib/graphQl/index.js:17:28)
    at Object.router.applyMiddleware (/opt/checklists_service/services/web-api-gateway/node_modules/jsonapi-server/lib/router.js:76:15)
    at Object.jsonApi.start (/opt/checklists_service/services/web-api-gateway/node_modules/jsonapi-server/lib/jsonApi.js:116:10)
    at Object.<anonymous> (/opt/checklists_service/services/index.js:41:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
According to ```joiConverter.js``` , it has limitation for non primitive array items - look at ```instructions``` above.
I've tried to remove the ```instructions```, but then i've got this error:
```
Error: Unable to parse Joi type, got {"isJoi":true,"_type":"any","_settings":null,"_valids":{"_set":[]},"_invalids":{"_set":[]},"_tests":[],"_refs":[],"_flags":{"presence":"required"},"_description":null,"_unit":null,"_notes":[],"_tags":[],"_examples":[],"_meta":[],"_inner":{}}
    at Object.joiConverter.simpleAttribute.joiScheme [as simpleAttribute] (/Users/yossialush/WebstormProjects/hello-world/node_modules/jsonapi-server/lib/graphQl/joiConverter.js:38:11)
    at Object.joiConverter.swap (/Users/yossialush/WebstormProjects/hello-world/node_modules/jsonapi-server/lib/graphQl/joiConverter.js:46:25)
    at Object.keys.forEach.attribute (/Users/yossialush/WebstormProjects/hello-world/node_modules/jsonapi-server/lib/graphQl/readTypes.js:41:30)
    at Array.forEach (native)
    at fields (/Users/yossialush/WebstormProjects/hello-world/node_modules/jsonapi-server/lib/graphQl/readTypes.js:36:46)
    at resolveThunk (/Users/yossialush/WebstormProjects/hello-world/node_modules/graphql/type/definition.js:115:40)
    at defineFieldMap (/Users/yossialush/WebstormProjects/hello-world/node_modules/graphql/type/definition.js:265:18)
    at GraphQLObjectType.getFields (/Users/yossialush/WebstormProjects/hello-world/node_modules/graphql/type/definition.js:235:44)
    at /Users/yossialush/WebstormProjects/hello-world/node_modules/graphql/type/schema.js:207:27
    at typeMapReducer (/Users/yossialush/WebstormProjects/hello-world/node_modules/graphql/type/schema.js:219:7)
```
Now ```responseType``` is making troubles, because it's an ```joi.object```

Most important is that those errors are being thrown during schema conversion for GraphQL feature, which in my case wasn't even enabled 
```
jsonApi.setConfig({
    graphiql: false
});
``` 
I'm not even interested in supporting GraphQL in this project, so it's weird that I'm still being affected by it.

**Comment by yossialush** [comment]
I see that https://github.com/holidayextras/jsonapi-server/pull/233 has solved it
