### ISSUE TITLE
Using the same chainhandler in multiple resources.

### ISSUE THREAD

**Issue by cahva** [holidayextras/jsonapi-server#298]
I don't know if this is more a documentation issue or a bug but it's a critical one.

Let's say that you want to have authentication handler in all of your resources which is what you have to do to determine if user is entitled to fetch/update/delete the resource.

I'm using the example server here to demonstrate what happens when you use the same chainhandler in two resources:

__Articles resource__ *removed timestampHandler from example*
```
const authenticationHandler = require('../handlers/authenticationHandler.js')

jsonApi.define({
  ...
  handlers: authenticationHandler.chain(articleHandler),
```

__Tags resource__ *added the auth handler to this resource*
```
const authenticationHandler = require('../handlers/authenticationHandler.js')

jsonApi.define({
  ...
  handlers: authenticationHandler.chain(tagHandler),
```

Now test with endpoint that triggers both resources:
```
GET http://localhost:16006/rest/tags?include=articles
```

Output with `DEBUG=jsonApi:handler:*` will be:
```
Before Search 1
After Search 1
  jsonApi:handler:search {"type":"tags","include":"articles","page":{"offset":0,"limit":50}} [null,[{"id":"7541a4de-4986-4597-81b9-cf31b6762486","type":"tags","name":"live","parent":{"type":"tags","id":"2a3bdea4-a889-480d-b886-104498c86f69"}},{"id":"2a3bdea4-a889-480d-b886-104498c86f69","type":"tags","name":"staging","parent":{"type":"tags","id":"6ec62f6d-9f82-40c5-b4f4-279ed1765492"}},{"id":"6ec62f6d-9f82-40c5-b4f4-279ed1765492","type":"tags","name":"building","parent":{"type":"tags","id":"68538177-7a62-4752-bc4e-8f971d253b42"}},{"id":"68538177-7a62-4752-bc4e-8f971d253b42","type":"tags","name":"development","parent":{"type":"tags","id":"8d196606-134c-4504-a93a-0d372f78d6c5"}},{"id":"8d196606-134c-4504-a93a-0d372f78d6c5","type":"tags","name":"planning","parent":null}],5] +0ms
  jsonApi:handler:search {"type":"tags","include":"articles","page":{"offset":0,"limit":50}} [null,[{"id":"7541a4de-4986-4597-81b9-cf31b6762486","type":"tags","name":"live","parent":{"type":"tags","id":"2a3bdea4-a889-480d-b886-104498c86f69"}},{"id":"2a3bdea4-a889-480d-b886-104498c86f69","type":"tags","name":"staging","parent":{"type":"tags","id":"6ec62f6d-9f82-40c5-b4f4-279ed1765492"}},{"id":"6ec62f6d-9f82-40c5-b4f4-279ed1765492","type":"tags","name":"building","parent":{"type":"tags","id":"68538177-7a62-4752-bc4e-8f971d253b42"}},{"id":"68538177-7a62-4752-bc4e-8f971d253b42","type":"tags","name":"development","parent":{"type":"tags","id":"8d196606-134c-4504-a93a-0d372f78d6c5"}},{"id":"8d196606-134c-4504-a93a-0d372f78d6c5","type":"tags","name":"planning","parent":null}],5] +1ms
Before Search 1
After Search 1
  jsonApi:handler:search {"filter":{"tags":["7541a4de-4986-4597-81b9-cf31b6762486","2a3bdea4-a889-480d-b886-104498c86f69","6ec62f6d-9f82-40c5-b4f4-279ed1765492","68538177-7a62-4752-bc4e-8f971d253b42","8d196606-134c-4504-a93a-0d372f78d6c5"]},"type":"articles","page":{"offset":0,"limit":50}} [null,[{"id":"de305d54-75b4-431b-adb2-eb6b9e546014","type":"articles","title":"NodeJS Best Practices","content":"na","created":"2016-01-05","views":10,"author":{"type":"people","id":"cc5cca2e-0dd8-4b95-8cfc-a11230e73116","meta":{"updated":"2010-11-06"}},"tags":[{"type":"tags","id":"7541a4de-4986-4597-81b9-cf31b6762486"}],"photos":[],"comments":[{"type":"comments","id":"3f1a89c2-eb85-4799-a048-6735db24b7eb"}],"meta":{"updated":"2011-05-10"}},{"id":"1be0913c-3c25-4261-98f1-e41174025ed5","type":"articles","title":"Linux Rocks","content":"na","created":"2015-11-11","views":20,"author":{"type":"people","id":"d850ea75-4427-4f81-8595-039990aeede5"},"tags":[{"type":"tags","id":"2a3bdea4-a889-480d-b886-104498c86f69"}],"photos":[{"type":"photos","id":"aab14844-97e7-401c-98c8-0bd5ec922d93"},{"type":"photos","id":"72695cbd-e9ef-44f6-85e0-0dbc06a269e8"}],"comments":[]},{"id":"d850ea75-4427-4f81-8595-039990aeede5","type":"articles","title":"How to AWS","content":"na","created":"2016-02-08","views":30,"author":{"type":"people","id":"32fb0105-acaa-4adb-9ec4-8b49633695e1"},"tags":[{"type":"tags","id":"8d196606-134c-4504-a93a-0d372f78d6c5"}],"photos":[{"type":"photos","id":"aab14844-97e7-401c-98c8-0bd5ec922d93"}],"comments":[]},{"id":"fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5","type":"articles","title":"Tea for Beginners","content":"na","created":"2015-06-23","views":40,"author":{"type":"people","id":"ad3aa89e-9c5b-4ac9-a652-6670f9f27587"},"tags":[{"type":"tags","id":"6ec62f6d-9f82-40c5-b4f4-279ed1765492"},{"type":"tags","id":"7541a4de-4986-4597-81b9-cf31b6762486"}],"photos":[{"type":"photos","id":"4a8acd65-78bb-4020-b9eb-2d058a86a2a0"}],"comments":[{"type":"comments","id":"6b017640-827c-4d50-8dcc-79d766abb408"}]}],4] +20ms
  jsonApi:handler:search {"filter":{"tags":["7541a4de-4986-4597-81b9-cf31b6762486","2a3bdea4-a889-480d-b886-104498c86f69","6ec62f6d-9f82-40c5-b4f4-279ed1765492","68538177-7a62-4752-bc4e-8f971d253b42","8d196606-134c-4504-a93a-0d372f78d6c5"]},"type":"articles","page":{"offset":0,"limit":50}} [null,[{"id":"de305d54-75b4-431b-adb2-eb6b9e546014","type":"articles","title":"NodeJS Best Practices","content":"na","created":"2016-01-05","views":10,"author":{"type":"people","id":"cc5cca2e-0dd8-4b95-8cfc-a11230e73116","meta":{"updated":"2010-11-06"}},"tags":[{"type":"tags","id":"7541a4de-4986-4597-81b9-cf31b6762486"}],"photos":[],"comments":[{"type":"comments","id":"3f1a89c2-eb85-4799-a048-6735db24b7eb"}],"meta":{"updated":"2011-05-10"}},{"id":"1be0913c-3c25-4261-98f1-e41174025ed5","type":"articles","title":"Linux Rocks","content":"na","created":"2015-11-11","views":20,"author":{"type":"people","id":"d850ea75-4427-4f81-8595-039990aeede5"},"tags":[{"type":"tags","id":"2a3bdea4-a889-480d-b886-104498c86f69"}],"photos":[{"type":"photos","id":"aab14844-97e7-401c-98c8-0bd5ec922d93"},{"type":"photos","id":"72695cbd-e9ef-44f6-85e0-0dbc06a269e8"}],"comments":[]},{"id":"d850ea75-4427-4f81-8595-039990aeede5","type":"articles","title":"How to AWS","content":"na","created":"2016-02-08","views":30,"author":{"type":"people","id":"32fb0105-acaa-4adb-9ec4-8b49633695e1"},"tags":[{"type":"tags","id":"8d196606-134c-4504-a93a-0d372f78d6c5"}],"photos":[{"type":"photos","id":"aab14844-97e7-401c-98c8-0bd5ec922d93"}],"comments":[]},{"id":"fa2a073f-8c64-4cbb-9158-b8f67a4ab9f5","type":"articles","title":"Tea for Beginners","content":"na","created":"2015-06-23","views":40,"author":{"type":"people","id":"ad3aa89e-9c5b-4ac9-a652-6670f9f27587"},"tags":[{"type":"tags","id":"6ec62f6d-9f82-40c5-b4f4-279ed1765492"},{"type":"tags","id":"7541a4de-4986-4597-81b9-cf31b6762486"}],"photos":[{"type":"photos","id":"4a8acd65-78bb-4020-b9eb-2d058a86a2a0"}],"comments":[{"type":"comments","id":"6b017640-827c-4d50-8dcc-79d766abb408"}]}],4] +0ms
```

As you can see it triggers the same jsonApi:handler:search 2 times for both resources. Because of this, it will definitely mess things up in storehandlers like mongodb.

To fix this behaviour, you will need to create different authenticationhandler per resource.

And finally to make this clear that you can't use the same chainhandler in different resources you can try to also chain timestampHandler in both resources:

__articles__
```
const timestampHandler = require('../handlers/timestampHandler.js')
const authenticationHandler = require('../handlers/authenticationHandler.js')

jsonApi.define({
  ...
  handlers: authenticationHandler.chain(timestampHandler).chain(articleHandler),
```

__tags__
```
const timestampHandler = require('../handlers/timestampHandler.js')
const authenticationHandler = require('../handlers/authenticationHandler.js')

jsonApi.define({
  ...
  handlers: authenticationHandler.chain(timestampHandler).chain(tagHandler),
```

This will crash the app with output:
```
[nodemon] starting `node example/server.js`
Before Initialise 1 articles
Before Initialise 2 articles
/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:8
  if (self.otherHandler instanceof ChainHandler) {
                        ^

RangeError: Maximum call stack size exceeded
    at ChainHandler.chain (/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:8:25)
    at ChainHandler.chain (/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:9:23)
    at ChainHandler.chain (/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:9:23)
    at ChainHandler.chain (/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:9:23)
    at ChainHandler.chain (/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:9:23)
    at ChainHandler.chain (/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:9:23)
    at ChainHandler.chain (/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:9:23)
    at ChainHandler.chain (/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:9:23)
    at ChainHandler.chain (/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:9:23)
    at ChainHandler.chain (/home/cahva/Projects/jsonapi-server/lib/ChainHandler.js:9:23)
[nodemon] app crashed - waiting for file changes before starting...
```

Could this also be related to my other issue #290?

**Comment by todoesverso** [comment]
This would be a great feature. Chain Handlers like "addTimeStamp" or "jwtAuth" or several others would be great to be able to re use them.

**Comment by SphtKr** [comment]
I may be missing something, but you just want to reuse the code, it's not important to reuse the same actual object, right? I read this issue before trying this myself (thanks!), and while I may be too early in my app to be able to see it, I tried this way and I *think* I'm being able to reuse an `authenticationHandler` just fine. I changed the way that the `authenticationHandler` module creates the handler and what it returns--instead of returning the handler, it returns a factory method that creates handlers:

```JavaScript
const jsonApi = require("jsonapi-server");

//const authenticationHandler = module.exports = new jsonApi.ChainHandler();
const authenticationHandlerFactory = module.exports = function(){
  var authenticationHandler = new jsonApi.ChainHandler();

  authenticationHandler.beforeFind = authenticationHandler.beforeSearch =
  authenticationHandler.beforeCreate = authenticationHandler.beforeDelete =
  function(req, callback) {
    //...
    callback(null, req);
    //...
  };

  return authenticationHandler;
};
```

And then in the `recordsHandler` module:

```JavaScript
const recordsHandler = require("./standardMemoryHandler");
//const authenticationHandler = require("./authenticationHandler");
const authenticationHandler = require("./authenticationHandler")();
//    Executes the factory function to create a new instance ---^

module.exports = authenticationHandler.chain(recordsHandler);
```

There's some inefficiency in this versus being able to actually use the same `authenticationHandler` object in multiple chains--but this at least lets me reuse the code easily.

**Comment by heller166** [comment]
This is a problem for me as well. Is this a bug or are we just missing how to use handlers properly?

**Comment by adamlc** [comment]
This isn't a bug, its how node loads modules. Returning a new instead from a function like @SphtKr has done should work 👍
